
import java.io.*;
import java.sql.*;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import java.util.Date;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Toshiba
 */
public class Bill extends javax.swing.JFrame {

    /**
     * Creates new form Bill
     */
    String logid;
    String payterm;
    Connection con;
    Statement stmt;
    java.util.Date dt = new java.util.Date();
    java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
    String d = sdf.format(dt);
    float tot = 0;
    int p = 0;
    int lst = 0;
    DecimalFormat df = new DecimalFormat("#.00");
    

    public Bill() {
        initComponents();
    }

    public Bill(String uid) {
        initComponents();
        logid = uid;
        ConnectionDB();
      
    }

    public final void ConnectionDB() {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/sampathstores", "root", "123");
            stmt = con.createStatement();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex + "DataAcces Failed!!Contact ADMIN!!");

        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, ex + "DataBase Connection Driver not Found!!Contact ADMIN!!");
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtbillid = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblinv = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtbillissue = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txttotal = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtstatus = new javax.swing.JTextField();
        txtcardno = new javax.swing.JTextField();
        lstpayterm = new javax.swing.JComboBox();
        btnback = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btngo = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtitemid = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtqnt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtprice = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtdscnt = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txttot = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtlogid = new javax.swing.JTextField();
        btnnew = new javax.swing.JButton();
        btnprint = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        txtpaid = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtbalance = new javax.swing.JTextField();
        btndone = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bill");
        setBackground(javax.swing.UIManager.getDefaults().getColor("Tree.selectionBackground"));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Bill ID          :");

        txtbillid.setEditable(false);
        txtbillid.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        tblinv.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tblinv.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Item", "Qnt", "Net Price", "Discount", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblinv.setEnabled(false);
        tblinv.setGridColor(new java.awt.Color(255, 255, 255));
        tblinv.setSelectionBackground(new java.awt.Color(153, 204, 255));
        tblinv.setSelectionForeground(new java.awt.Color(0, 0, 0));
        tblinv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblinvMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblinv);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Issued By   :");

        txtbillissue.setEditable(false);
        txtbillissue.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Total          :");

        txttotal.setEditable(false);
        txttotal.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(txtbillid, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txtbillissue, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtbillid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtbillissue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txttotal))
                .addContainerGap())
        );

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Pay Term");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Cardno");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Status");

        txtstatus.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        txtcardno.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        lstpayterm.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lstpayterm.setForeground(javax.swing.UIManager.getDefaults().getColor("nbProgressBar.Foreground"));
        lstpayterm.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select","Cash", "Credit Card" }));
        lstpayterm.setSelectedItem("Select");
        lstpayterm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lstpaytermActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtcardno)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtstatus, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lstpayterm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 75, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(lstpayterm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcardno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtstatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnback.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnback.setText("Back");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });

        btngo.setBackground(java.awt.SystemColor.textHighlight);
        btngo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btngo.setText("Go!");
        btngo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngoActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Item ID              :");

        txtitemid.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtitemid.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtitemidMouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Quantity             :");

        txtqnt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Price(1 unit)       :");

        txtprice.setEditable(false);
        txtprice.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtprice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtpriceMouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Discount (%)     :");

        txtdscnt.setEditable(false);
        txtdscnt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtdscnt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtdscntMouseClicked(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Total                   :");

        txttot.setEditable(false);
        txttot.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txttot.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txttotMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtitemid)
                            .addComponent(txtqnt)
                            .addComponent(txtprice)
                            .addComponent(txtdscnt)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txttot))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 140, Short.MAX_VALUE)
                        .addComponent(btngo)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtitemid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtqnt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtdscnt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(txttot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btngo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel8.setText("User :");

        txtlogid.setEditable(false);

        btnnew.setBackground(new java.awt.Color(0, 153, 204));
        btnnew.setFont(new java.awt.Font("Goudy Old Style", 1, 18)); // NOI18N
        btnnew.setForeground(java.awt.Color.blue);
        btnnew.setText("New");
        btnnew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnewActionPerformed(evt);
            }
        });

        btnprint.setFont(new java.awt.Font("Orator Std", 1, 24)); // NOI18N
        btnprint.setForeground(new java.awt.Color(0, 0, 255));
        btnprint.setText("Print");
        btnprint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprintActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Pay");

        txtpaid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpaidActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("Balance");

        txtbalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbalanceActionPerformed(evt);
            }
        });

        btndone.setText("Done");
        btndone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndoneActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtbalance, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(txtpaid, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(btndone)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtpaid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btndone))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtbalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnback))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtlogid, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnprint)
                            .addComponent(btnnew, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtlogid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(119, 119, 119)
                        .addComponent(btnprint, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnnew)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(btnback)))
                        .addGap(196, 196, 196))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(210, 210, 210))))
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        this.setVisible(false);
        new Home(logid).setVisible(true);
    }//GEN-LAST:event_btnbackActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        txtlogid.setText(logid);
        txtbillissue.setText(logid);
        try {

            String billid = "Select invno from invfl order by invno desc limit 1";
            ResultSet rs2 = stmt.executeQuery(billid);
            rs2.next();
            int invno1 = rs2.getInt("invno");
            if (!rs2.next()) {
                int invno2 = invno1 + 1;
                String bid = Integer.toString(invno2);
                txtbillid.setText(bid);
            }

        } catch (SQLException ex) {
            String bid = "1";
            txtbillid.setText(bid);
        }


    }//GEN-LAST:event_formWindowOpened

    private void btnnewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnewActionPerformed

        this.setVisible(false);
        new Bill(logid).setVisible(true);
    }//GEN-LAST:event_btnnewActionPerformed

    private void btngoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngoActionPerformed

        try {

            int iid = Integer.parseInt(txtitemid.getText());
            String setitemname = "Select itemname,packsize from itemfl where itemcd='" + iid + "'";
            ResultSet rs3 = stmt.executeQuery(setitemname);
            rs3.next();
            String itemname = rs3.getString("itemname");
            float itemqtyt = rs3.getFloat("packsize");
            String updatepack = "Update itemfl set packsize=packsize-'" + txtqnt.getText() + "' where itemcd='" + iid + "'";
            stmt.executeUpdate(updatepack);
            int bid = Integer.parseInt(txtbillid.getText());
            float iqt = Float.parseFloat(txtqnt.getText());
            float nprice = Float.parseFloat(txtprice.getText());
            float dscnt = Float.parseFloat(txtdscnt.getText());
            float price = Float.parseFloat(txttot.getText());
            float citem = 0;
            float cprice = 0;
            int check = 0;
            String chid = "Select itemcd from invfl where invno='" + bid + "' ";
            ResultSet rsid = stmt.executeQuery(chid);
            while (rsid.next()) {
                if (rsid.getInt("itemcd") == iid) {
                    check++;
                }
            }
            if (check != 0) {
                String chsql = "Select Item_Qnt,Price from invfl where itemcd='" + iid + "'AND invno='" + bid + "'  ";
                ResultSet rsch = stmt.executeQuery(chsql);
                rsch.next();
                citem = rsch.getFloat("Item_Qnt");
                cprice = rsch.getFloat("Price");
                float nwqnt = iqt + citem;
                float nwprice = cprice + tot;
                stmt.executeUpdate("Update invfl SET Item_Qnt='" + nwqnt + "',  Price='" + nwprice + "'  where itemcd='" + iid + "' AND invno='" + bid + "' ");
            } else {
                String inv = "Insert into invfl values('" + bid + "','" + d + "','" + iid + "','" + itemname + "','" + iqt + "','" + nprice + "','" + dscnt + "','" + price + "','" + payterm + "','" + txtcardno.getText() + "','" + txtstatus.getText() + "','" + logid + "')";
                stmt.executeUpdate(inv);
            }
            String tblsql = "Select Item_Name,Item_Qnt,Net_Price,Discount,Price from invfl where invno= '" + bid + "'";
            ResultSet rs1 = stmt.executeQuery(tblsql);
            tblinv.setModel(DbUtils.resultSetToTableModel(rs1));
            String settotal = "Select sum(price) as tot from invfl where invno='" + bid + "'";
            ResultSet rstot = stmt.executeQuery(settotal);

            rstot.next();
            float total = rstot.getFloat("tot");
            txttotal.setText(df.format(total));
            ++lst;
            tot = 0;
            txtitemid.setText("");
            txtqnt.setText("");
            txtprice.setText("");
            txtdscnt.setText("");
            txttot.setText("");
            if (lst != 0) {
                lstpayterm.setEnabled(false);
                txtcardno.setEditable(false);
                txtstatus.setEditable(false);
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);

        }

    }//GEN-LAST:event_btngoActionPerformed

    private void txtpriceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtpriceMouseClicked
        try {
            int iid = Integer.parseInt(txtitemid.getText());
            String setitemprice = "Select sellprice from itemfl where itemcd='" + iid + "'";
            ResultSet rsa;
            rsa = stmt.executeQuery(setitemprice);
            rsa.next();
            int price = rsa.getInt("sellprice");
            String pr = Integer.toString(price);
            txtprice.setText(pr);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Invalid Item Code!!!!");
        }
    }//GEN-LAST:event_txtpriceMouseClicked

    private void lstpaytermActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lstpaytermActionPerformed
        payterm = (String) lstpayterm.getSelectedItem();
        if (payterm == "Cash") {

            txtcardno.setEditable(false);
            txtstatus.setEditable(false);
            txtpaid.setEditable(true);
            txtbalance.setEditable(true);

        } else {
            txtcardno.setEditable(true);
            txtstatus.setEditable(true);
            txtpaid.setEditable(false);
            txtbalance.setEditable(false);
        }
    }//GEN-LAST:event_lstpaytermActionPerformed

    private void txttotMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txttotMouseClicked

        float dscnt = Float.parseFloat(txtdscnt.getText());
        float price = Integer.parseInt(txtprice.getText());
        float qnt = Integer.parseInt(txtqnt.getText());
        float calds = (dscnt / 100) * price;
        tot = (price - calds) * qnt;

        String totl = Float.toString(tot);
        txttot.setText(totl);

    }//GEN-LAST:event_txttotMouseClicked

    private void btnprintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprintActionPerformed

        try {

            if (payterm == "Cash" && txtpaid.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Enter paid amount!!!!");
            } else if (p == 0) {
                ++p;
                btnprint.setEnabled(false);
                String sqlfl = "Select itemcd,Item_Name,Item_Qnt,Net_Price,Discount,Price from invfl  where invno='" + txtbillid.getText() + "' order by itemcd";
                File f = new File("C:\\Users\\Nilusha De Silva\\Documents\\NetBeansProjects\\BillingSystem\\Bills\\"+txtbillid.getText() + ".txt");
                FileWriter fw = new FileWriter(f, true);
                PrintWriter w = new PrintWriter(fw);
                w.append("\t\t\t\t\tSAMPATH STORES - HORANA");
                w.println();
                w.append("\t\t\t\t\t\tTel-0114595062");
                w.println();
                w.append("\t\t\tIssued By :" + txtlogid.getText() + "\t\t\t\tPay term :" + payterm);
                w.println();
                w.append("\t\t\tDate/Time :" + d+"\t\tBill ID :" + txtbillid.getText());
                w.println();
                w.append("\t\t\tItemcd \tItem_Name\tqnt\tnet price\tdiscount\tvalue");
                w.println();
                ResultSet rsf = stmt.executeQuery(sqlfl);
                while (rsf.next()) {

                    w.append("\t\t\t" + rsf.getInt("itemcd") + "\t" + rsf.getString("Item_Name") + "\t\t" + rsf.getFloat("Item_Qnt") + "\t" + rsf.getFloat("Net_Price") + "\t" + rsf.getFloat("Discount") + "\t" + rsf.getFloat("Price"));
                    w.println();

                }
                w.append("\t\t\tTotal:   " + txttotal.getText());
                if (payterm == "Cash") {
                    w.println();
                    w.append("\t\t\tPay :    " + txtpaid.getText());
                    w.println();
                    w.append("\t\t\tBalance :    " + txtbalance.getText());
                } else {
                    w.println();
                    txtpaid.setText(txttotal.getText());
                    txtbalance.setText("0");
                    w.append("\t\t\tPay :    " + txttotal.getText());
                    w.println();
                    w.append("\t\t\tBalance :    " + 0);
                }

                w.println();
                w.append("\t\t\t\t\t\tTHANK YOU!!!");
                w.println();
                w.append("\t\t\t\t\t\tCome Again!!!");
                w.println();
                w.append("\t\t\t(Project of NIBM 13.1 pt batch)");

                w.close();
                btngo.setEnabled(false);

            } else {
                btnprint.setEnabled(false);
            }
        } catch (SQLException | IOException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }


    }//GEN-LAST:event_btnprintActionPerformed

    private void txtpaidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpaidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpaidActionPerformed

    private void txtbalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbalanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbalanceActionPerformed

    private void btndoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndoneActionPerformed
        String tot = txttotal.getText();
        String pay = txtpaid.getText();
        float balance = Float.parseFloat(pay) - Float.parseFloat(tot);
        DecimalFormat df = new DecimalFormat("#.00");
        txtbalance.setText(df.format(balance));
    }//GEN-LAST:event_btndoneActionPerformed

    private void txtdscntMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtdscntMouseClicked
        try {
            int iid = Integer.parseInt(txtitemid.getText());
            String setitemprice = "Select discount  from itemfl where itemcd='" + iid + "'";
            ResultSet rsa;
            rsa = stmt.executeQuery(setitemprice);
            rsa.next();
            float dscnt = rsa.getFloat("discount");
            String dsc = Float.toString(dscnt);
            txtdscnt.setText(dsc);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Invalid Item Code!!!!");
        }
    }//GEN-LAST:event_txtdscntMouseClicked

    private void txtitemidMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtitemidMouseClicked
        if (payterm == "Credit Card" && (txtcardno.getText().equals("") || txtstatus.getText().equals(""))) {
            JOptionPane.showMessageDialog(null, "Enter Credit Card details!!!");

        }
        if (payterm == null || payterm == "Select") {
            JOptionPane.showMessageDialog(null, "Select pay term!!!");
        }


    }//GEN-LAST:event_txtitemidMouseClicked

    private void tblinvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblinvMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblinvMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bill().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnback;
    private javax.swing.JButton btndone;
    private javax.swing.JButton btngo;
    private javax.swing.JButton btnnew;
    private javax.swing.JButton btnprint;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox lstpayterm;
    private javax.swing.JTable tblinv;
    private javax.swing.JTextField txtbalance;
    private javax.swing.JTextField txtbillid;
    private javax.swing.JTextField txtbillissue;
    private javax.swing.JTextField txtcardno;
    private javax.swing.JTextField txtdscnt;
    private javax.swing.JTextField txtitemid;
    private javax.swing.JTextField txtlogid;
    private javax.swing.JTextField txtpaid;
    private javax.swing.JTextField txtprice;
    private javax.swing.JTextField txtqnt;
    private javax.swing.JTextField txtstatus;
    private javax.swing.JTextField txttot;
    private javax.swing.JTextField txttotal;
    // End of variables declaration//GEN-END:variables
}
