
import java.io.*;
import java.sql.*;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import java.util.Date;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Toshiba
 */
public class DayReport extends javax.swing.JFrame {

    /**
     * Creates new form DayReport
     */
    Connection con;
    Statement stmt;
    String logid;
    int year;
    int month;
    int day;
    float total1;
    String date;
    int done = 0;
    java.util.Date dt = new java.util.Date();
    java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
    String d = sdf.format(dt);

    private DayReport() {
        initComponents();

    }

    public DayReport(int y, int m, int d, String uid) {
        initComponents();
        year = y;
        month = m;
        day = d;
        logid = uid;
        ConnectionDB();
        TableDB();
        Total();
        date = Integer.toString(year) + "-" + Integer.toString(month) + "-" + Integer.toString(day);
    }

    public final void ConnectionDB() {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/sampathstores", "root", "123");
            stmt = con.createStatement();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex + "DataAcces Failed!!Contact ADMIN!!");

        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, ex + "DataBase Connection Driver not Found!!Contact ADMIN!!");
        }

    }

    public void TableDB() {
        try {

            String tblsql = "Select invdate,itemcd,Item_Name,Item_Qnt ,Net_Price,Discount,Price from invfl where DAY(invdate)= '" + day + "'  AND MONTH(invdate) = '" + month + "' AND YEAR(invdate) ='" + year + "' ";
            ResultSet rs1 = stmt.executeQuery(tblsql);
            boolean val = rs1.next();
            if (val == false) {
                JOptionPane.showMessageDialog(null, "No results founds for this Month and Year");
                btnprint.setEnabled(false);
            } else {
                tblReport.setModel(DbUtils.resultSetToTableModel(rs1));
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);

        }

    }

    public void Total() {
        try {

            String count = "Select SUM(Price) AS total  from invfl where  DAY(invdate)= '" + day + "'  AND MONTH(invdate) = '" + month + "' AND YEAR(invdate) ='" + year + "'  ";
            ResultSet rs1 = stmt.executeQuery(count);
            rs1.next();
            total1 = rs1.getFloat("total");
            txttotal.setText(Float.toString(total1));

        } catch (SQLException ex) {

            JOptionPane.showMessageDialog(null, ex);

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtlogid = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblReport = new javax.swing.JTable();
        btnback = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txttotal = new javax.swing.JTextField();
        btnprint = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Day Report");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setBackground(javax.swing.UIManager.getDefaults().getColor("ToggleButton.shadow"));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setForeground(javax.swing.UIManager.getDefaults().getColor("List.selectionBackground"));
        jLabel1.setText("Selling Report :");

        jLabel13.setText("User :");

        txtlogid.setEditable(false);

        tblReport.setBackground(javax.swing.UIManager.getDefaults().getColor("PropSheet.setBackground"));
        tblReport.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblReport);

        btnback.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnback.setText("Back");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(javax.swing.UIManager.getDefaults().getColor("ToolBar.dockingForeground"));
        jLabel3.setText("Total          :");

        txttotal.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        btnprint.setFont(new java.awt.Font("Orator Std", 1, 16)); // NOI18N
        btnprint.setForeground(new java.awt.Color(0, 0, 255));
        btnprint.setText("Print");
        btnprint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprintActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(btnback)
                .addGap(240, 240, 240)
                .addComponent(btnprint)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 824, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(635, 635, 635)
                            .addComponent(jLabel3)
                            .addGap(18, 18, 18)
                            .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(622, 622, 622)
                            .addComponent(jLabel13)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtlogid, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(18, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnback)
                    .addComponent(btnprint))
                .addGap(25, 25, 25))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(txtlogid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 371, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(txttotal))
                    .addGap(31, 31, 31)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        this.setVisible(false);
        new DailyReport(logid).setVisible(true);
    }//GEN-LAST:event_btnbackActionPerformed

    private void btnprintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprintActionPerformed

        try {
            if (done == 0) {
                ++done;
                String sqlfl = "Select invdate,itemcd,Item_Name,Item_Qnt ,Net_Price,Discount,Price from invfl where DAY(invdate)= '" + day + "'  AND MONTH(invdate) = '" + month + "' AND YEAR(invdate) ='" + year + "' ";
                
                PrintWriter writer = new PrintWriter("C:\\Users\\Toshiba\\Documents\\NetBeansProjects\\BillingSystem\\Daily_Reports\\" + date + ".txt", "UTF-8");
                writer.println("\t\t\t\t\tSAMPATH STORES - HORANA");
                writer.println("\t\t\t\t\t\tTel-0114595062");
                writer.println("\t\t\tIssued By :" + txtlogid.getText());
                writer.println("\t\t\t\t\tDaily Report");
                writer.println("\t\t\t\t\tReport For :" + date);
                 writer.println();
                 writer.println("\t\t\t\tInvdate \t\tItemcd\t\tItem_Name\tItem_Qnt\t\tNet_price\t\tDiscount\t  value");
                writer.println();
                ResultSet rsf = stmt.executeQuery(sqlfl);
                while (rsf.next()) {
                    writer.println("\t\t\t" + rsf.getString("invdate") + "\t" + rsf.getInt("itemcd") + "\t\t" + rsf.getString("Item_Name") + "\t\t" + rsf.getFloat("Item_Qnt") + "\t\t" + rsf.getFloat("Net_Price") + "\t\t" + rsf.getFloat("Discount") + "\t" + rsf.getFloat("Price"));
                }
                writer.println();
                writer.println("\t\t\t\t\t\t\t\t\t\t\t\t\t\t   Total:   " + txttotal.getText());
                writer.close();
            } else {
                btnprint.setEnabled(false);
            }

        } catch (IOException | SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_btnprintActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        txtlogid.setText(logid);

    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DayReport.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DayReport.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DayReport.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DayReport.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DayReport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnback;
    private javax.swing.JButton btnprint;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblReport;
    private javax.swing.JTextField txtlogid;
    private javax.swing.JTextField txttotal;
    // End of variables declaration//GEN-END:variables
}
